group = "com.tovli.edge_intelligence"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.7.3"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    namespace = "com.tovli.edge_intelligence"
    compileSdk = 35

    defaultConfig {
        minSdk = 24
    }

    sourceSets {
        main.jniLibs.srcDirs = ["src/main/jniLibs"]
    }
}
